# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        landscape_show:
            quality: 75
            filters:
                thumbnail:
                    size:  [600, 360]
                    mode:  outbound

        edit_page:
            quality: 75
            filters:
                thumbnail:
                    size:  [290, 200]
                    mode:  outbound

          
